{{- if .Values.upstream.volumes.sharedHome.efs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}-efs-shared-home
  labels:
    {{- include "common.labels.commonLabels" . | nindent 4 }}
spec:
  volumeName: {{ include "common.names.fullname" . }}-shared-home-pv
  accessModes:
  {{ range .Values.upstream.volumes.sharedHome.efs.persistentVolumeClaim.accessModes }}
    - {{ . }}
  {{- end }}
  {{- if .Values.upstream.volumes.sharedHome.efs.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ .Values.upstream.volumes.sharedHome.efs.persistentVolumeClaim.storageClassName | quote }}
  {{- end }}
  {{- with .Values.upstream.volumes.sharedHome.efs.persistentVolumeClaim.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- else if .Values.upstream.volumes.sharedHome.nfs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}-nfs-shared-home
  labels:
    {{- include "common.labels.commonLabels" . | nindent 4 }}
spec:
  volumeName: {{ include "common.names.fullname" . }}-shared-home-pv
  accessModes:
  {{ range .Values.upstream.volumes.sharedHome.nfs.persistentVolumeClaim.accessModes }}
    - {{ . }}
  {{- end }}
  {{- if .Values.upstream.volumes.sharedHome.nfs.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ .Values.upstream.volumes.sharedHome.nfs.persistentVolumeClaim.storageClassName | quote }}
  {{- end }}
  {{- with .Values.upstream.volumes.sharedHome.nfs.persistentVolumeClaim.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}  
